# Intervalos de tempo em milissegundos
DISPLAY_INTERVAL_VIAGEM = 0.2
DISPLAY_INTERVAL_VELOCIDADE = 0.1
DISPLAY_INTERVAL_TOTAL = 0.5
DISPLAY_INTERVAL_TIME = 1.0
DEFAULT_REPETITIONS = 10
DEFAULT_DELAY = 0
